# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('ASST_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ASST_NAME', models.CharField(max_length=250)),
                ('DATE_OF_BIRTH', models.DateField()),
                ('AGE_GROUP', models.IntegerField(choices=[(1, '0-10'), (2, '11-20'), (3, '21-30'), (4, '31-40'), (5, '41-50'), (6, '51-60'), (7, '61-70'), (8, '71-80'), (9, '81-90')])),
                ('GENDER', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('PREF_LANG_1', models.CharField(max_length=25)),
                ('PREF_LANG_2', models.CharField(max_length=25)),
                ('TRAINED_SKILL', models.CharField(max_length=25)),
                ('TRAINED_LEVEL', models.CharField(max_length=25)),
                ('PRODUCT_SKILL', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'pg_assistance',
            },
        ),
        migrations.CreateModel(
            name='AssistanceAvail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME_IN', models.DateField()),
                ('TIME_OUT', models.DateField()),
                ('AVAILABILITY', models.BooleanField()),
                ('ASST_ID', models.ForeignKey(db_column='ASST_ID', on_delete=django.db.models.deletion.CASCADE, to='pingow_api.Assistance')),
            ],
            options={
                'db_table': 'pg_assistance_avail',
            },
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('BEACON_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pg_beacon',
            },
        ),
        migrations.CreateModel(
            name='BeaconRelationship',
            fields=[
                ('RELATIONSHIP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BEACON_ID_SEC', models.IntegerField()),
                ('RELATIONSHIP_TYPE', models.CharField(choices=[('neighbour', 'neighbour'), ('self', 'self'), ('no relationship', 'no relationship')], default='no relationship', max_length=25)),
                ('BEACON_ID', models.ForeignKey(db_column='BEACON_ID', on_delete=django.db.models.deletion.CASCADE, to='pingow_api.Beacon')),
            ],
            options={
                'db_table': 'pg_beacon_relationship',
            },
        ),
        migrations.CreateModel(
            name='Crowd',
            fields=[
                ('CROWD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CROWD_LEVEL', models.IntegerField(choices=[(1, 'Green'), (2, 'Orange'), (3, 'Red')], default=1)),
            ],
            options={
                'db_table': 'pg_crowd',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CUSTOMER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CUSTOMER_NAME', models.CharField(max_length=250)),
                ('DATE_OF_BIRTH', models.DateField()),
                ('AGE_GROUP', models.IntegerField(choices=[(1, '0-10'), (2, '11-20'), (3, '21-30'), (4, '31-40'), (5, '41-50'), (6, '51-60'), (7, '61-70'), (8, '71-80'), (9, '81-90')])),
                ('GENDER', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('PREF_LANG_1', models.CharField(max_length=25)),
                ('PREF_LANG_2', models.CharField(max_length=25)),
                ('USER_TYPE', models.CharField(max_length=25)),
                ('DATE_REG', models.DateField()),
            ],
            options={
                'db_table': 'pg_customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('TRANSACTION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CUSTOMER_ID', models.IntegerField()),
                ('SUB_CAT_ID', models.IntegerField()),
                ('SHOP_ID', models.IntegerField()),
                ('ASST_ID', models.IntegerField()),
                ('CREATION_DATE', models.DateField()),
                ('TIME_OF_ENTER', models.DateField(null=True)),
                ('TIME_OF_EXIT', models.DateField(null=True)),
                ('ASST_SVC_RATE', models.IntegerField()),
                ('OVERALL_RATE', models.IntegerField()),
                ('COMMENTS', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pg_customer_trans',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('SHOP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SHOP_NAME', models.CharField(max_length=250)),
                ('DATE_REG', models.DateField()),
                ('DATE_DEREG', models.DateField()),
                ('W_FRIENDLY', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('ASSIST_AVAIL', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('AVG_RATING', models.IntegerField()),
                ('VISITS', models.IntegerField()),
            ],
            options={
                'db_table': 'pg_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopSubCatReference',
            fields=[
                ('REF_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SUB_CAT_ID', models.IntegerField()),
                ('SHOP_ID', models.ForeignKey(db_column='SHOP_ID', on_delete=django.db.models.deletion.CASCADE, to='pingow_api.Shop')),
            ],
            options={
                'db_table': 'pg_shop_subcat_ref',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('SUB_CAT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SUB_CAT_NAME', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'pg_sub_cat',
            },
        ),
        migrations.AddField(
            model_name='crowd',
            name='SHOP_ID',
            field=models.ForeignKey(db_column='SHOP_ID', on_delete=django.db.models.deletion.CASCADE, to='pingow_api.Shop'),
        ),
        migrations.AddField(
            model_name='beacon',
            name='SHOP_ID',
            field=models.ForeignKey(db_column='SHOP_ID', on_delete=django.db.models.deletion.CASCADE, to='pingow_api.Shop'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='SHOP_ID',
            field=models.ForeignKey(db_column='SHOP_ID', on_delete=django.db.models.deletion.CASCADE, to='pingow_api.Shop'),
        ),
    ]
