# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingow_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransactionStatus',
            fields=[
                ('TRANSACTION_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'pg_customer_trans_status',
            },
        ),
    ]
